// <auto-generated />
using System;
using CarRentalManagmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalManagmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241214155620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />

    }
}
